---
# molecule file for claco.shell

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: "../../.yamllint"
platforms:
  - name: popos-20.04
    image: popos:20.04
  - name: ubuntu-focal
    image: ubuntu:focal
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      c: "../../.ansible-lint"
      R: "../../rules"
scenario:
  name: default
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 120