---
# defaults file for claco.docker

docker_package_name:
docker_package_version: "latest"
docker_python_packages:
  - name: "docker"
    version: "latest"
docker_python_support: true
docker_python_virtualenv: "{{ pip_virtualenv }}"
